name: Simple Python CI + Slack Notify

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Dodajemy PYTHONPATH, żeby tests mogły importować app
      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$(pwd)" >> $GITHUB_ENV

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Lint (flake8)
        id: flake8
        run: flake8 .
        continue-on-error: true

      - name: Run tests (pytest)
        id: pytest
        run: pytest -v
        continue-on-error: true

      - name: Slack Notification
        if: always()
        run: |
          if [[ "${{ steps.flake8.outcome }}" == "failure" ]] || [[ "${{ steps.pytest.outcome }}" == "failure" ]]; then
            STATUS="FAILED"
          else
            STATUS="SUCCESS"
          fi

          MSG="$STATUS: $GITHUB_REPOSITORY @ ${GITHUB_SHA::7} on $GITHUB_REF_NAME"

          curl -X POST -H 'Content-type: application/json' \
            --data "{\"text\":\"$MSG\"}" \
            "${{ secrets.SLACK_WEBHOOK_URL }}"
