name: Python CI + Docker + Slack Notify

on: [push, pull_request]

env:
  RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      # 3. Install dependencies
      - name: Install dependencies
        run: pip install -r requirements.txt jq

      # 4. Run flake8
      - name: Run flake8
        id: flake8
        run: flake8 .
        continue-on-error: true

      # 5. Run pylint
      - name: Run pylint
        id: pylint
        run: pylint app/ tests/
        continue-on-error: true

      # 6. Run pytest
      - name: Run pyte


