name: Slack Test

on:
  workflow_dispatch:  # ręczne uruchamianie

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send test notification to Slack
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{"text":"✅ Testowe powiadomienie z GitHub Actions działa!"}' \
          ${{ secrets.SLACK_WEBHOOK_URL }}

