name: Simple Python CI + Slack Notify

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout repository
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Set up Python
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      # 3. Install dependencies
      - name: Install dependencies
        run: pip install -r requirements.txt

      # 4. Run flake8
      - name: Lint (flake8)
        id: flake8
        run: flake8 .
        continue-on-error: true

      # 5. Run tests
      - name: Run tests (pytest)
        id: pytest
        run: pytest -v
        continue-on-error: true

      # 6. Notify Slack
      - name: Slack Notification
        if: always()
        run: |
          # Sprawdzamy wyniki poprzednich kroków
          if [[ "${{ steps.flake8.outcome }}" == "failure" ]] || [[ "${{ steps.pytest.outcome }}" == "failure" ]]; then
            STATUS="FAILED"
          else
            STATUS="SUCCESS"
          fi

          MSG="$STATUS: $GITHUB_REPOSITORY @ ${GITHUB_SHA::7} on $GITHUB_REF_NAME"

          # Wysyłamy prosty JSON do Slacka bez użycia znaków specjalnych
          curl -X POST -H 'Content-type: application/json' \
            --data "{\"text\":\"$MSG\"}" \
            "${{ secrets.SLACK_WEBHOOK_URL }}"



