jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run static analysis (flake8)
        run: flake8 .

      - name: Run static analysis (pylint)
        run: pylint app/ tests/

      - name: Run tests
        run: pytest -v

      # --- POWIADOMIENIA SLACK ---
      - name: Notify Slack (success)
        if: success()
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          MSG="✅ SUCCESS: $GITHUB_REPOSITORY @ ${GITHUB_SHA::7} on $GITHUB_REF_NAME"
          curl -X POST -H 'Content-type: application/json' \
            --data "{\"text\":\"$MSG\"}" \
            "$SLACK_WEBHOOK_URL"

      - name: Notify Slack (failure)
        if: failure()
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          MSG="❌ FAILED: $GITHUB_REPOSITORY @ ${GITHUB_SHA::7} on $GITHUB_REF_NAME"
          curl -X POST -H 'Content-type: application/json' \
            --data "{\"text\":\"$MSG\"}" \
            "$SLACK_WEBHOOK_URL"

