name: Python CI + Slack Notify

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout
        uses: actions/checkout@v4

    
      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$(pwd)" >> $GITHUB_ENV

 
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          sudo apt-get update && sudo apt-get install -y jq

      - name: Lint (flake8)
        id: flake8
        run: flake8 .
        continue-on-error: true

      
      - name: Run tests (pytest)
        id: pytest
        run: pytest -v
        continue-on-error: true

      - name: Slack Notification
        if: always()
        run: |
          # Determine SUCCESS or FAILED based on previous steps
          STATUS="SUCCESS"
          if [[ "${{ steps.flake8.outcome }}" == "failure" ]] || [[ "${{ steps.pytest.outcome }}" == "failure" ]]; then
            STATUS="FAILED"
          fi

          # Compose simple ASCII message
          MSG="$STATUS: $GITHUB_REPOSITORY @ ${GITHUB_SHA::7} on $GITHUB_REF_NAME"

          # Generate valid JSON safely with jq
          JSON_PAYLOAD=$(jq -n --arg msg "$MSG" '{text: $msg}')

          # Send notification to Slack (no curl errors)
          curl -X POST -H 'Content-type: application/json' \
               --data-raw "$JSON_PAYLOAD" \
               "${{ secrets.SLACK_WEBHOOK_URL }}"
