name: Python CI + Docker + Slack Notify

on: [push, pull_request]

env:
  RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install -r requirements.txt

      # Lint flake8
      - name: Run static analysis (flake8)
        run: flake8 .
        continue-on-error: true
        id: flake8_step

      # Lint pylint
      - name: Run static analysis (pylint)
        run: pylint app/ tests/
        continue-on-error: true
        id: pylint_step

      # Testy pytest
      - name: Run tests
        run: pytest -v
        continue-on-error: true
        id: pytest_step

      # --- POWIADOMIENIE SLACK ---
      - name: Notify Slack
        if: always()  # <- krok wykona się niezależnie od błędów
        run: |
          FAILED=0
          for STEP in flake8_step pylint_step pytest_step; do
            if [[ "${{ steps.$STEP.outcome }}" == "failure" ]]; then
              FAILED=1
            fi
          done

          if [[ $FAILED -eq 1 ]]; then
            STATUS="❌ FAILED"
          else
            STATUS="✅ SUCCESS"
          fi

          MSG="$STATUS: $GITHUB_REPOSITORY @ ${GITHUB_SHA::7} on $GITHUB_REF_NAME → $RUN_URL"
          curl -X POST -H 'Content-type: application/json' \
            --data "{\"text\":\"$MSG\"}" \
            "${{ secrets.SLACK_WEBHOOK_URL }}"

  docker:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          tags: ci-docker:latest

