name: Python CI + Slack Notify

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout repo
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Set PYTHONPATH (aby pytest widział moduł app)
      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$(pwd)" >> $GITHUB_ENV

      # 3. Setup Python
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      # 4. Install dependencies + jq
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          sudo apt-get update && sudo apt-get install -y jq

      # 5. Run flake8
      - name: Lint (flake8)
        id: flake8
        run: flake8 .
        continue-on-error: true

      # 6. Run pytest
      - name: Run tests (pytest)
        id: pytest
        run: pytest -v
        continue-on-error: true

      # 7. Slack Notification
      - name: Slack Notification
        if: always()
        run: |
          STATUS="SUCCESS"
          if [[ "${{ steps.flake8.outcome }}" == "failure" ]] || [[ "${{ steps.pytest.outcome }}" == "failure" ]]; then
            STATUS="FAILED"
          fi

          MSG="$STATUS: $GITHUB_REPOSITORY @ ${GITHUB_SHA::7} on $GITHUB_REF_NAME"

          # Tworzymy poprawny JSON
          JSON_PAYLOAD=$(jq -n --arg msg "$MSG" '{text: $msg}')

          # Wysyłamy powiadomienie Slack (bez błędów curl)
          curl -X POST -H 'Content-type: application/json' \
               --data-raw "$JSON_PAYLOAD" \
               "${{ secrets.SLACK_WEBHOOK_URL }}"

